In [1]:
import warnings
warnings.filterwarnings('ignore')

In [2]:
from tpot import TPOTClassifier
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix

In [3]:
# load raw data
pref = ['C4_1_','C4_5_','C4_6_', 'C4_8_', 'C4_10_']
#pref = ['C4_10_']
df_d = {}
for i in range(len(pref)):
    fname   = pref[i] + 'rawdata_open.csv'
    df_d[i] = pd.read_csv(fname)
#df = pd.read_csv('C4_10_features.csv')
#df_d[4]

In [4]:
df1 = pd.concat(df_d.values(), ignore_index=True)
#ii = 3
#df = df_d[ii]  
df1

,x1,x2,x3,x4,x5,x6,x7,x8,x9,x10,...,x92,x93,x94,x95,x96,x97,x98,x99,x100,Class
0,-23.828852,-7.226783,-0.976592,-3.808710,-5.566576,-4.980621,-4.492325,0.683615,11.816767,16.406751,...,48.048341,53.126621,46.192816,36.719871,38.380078,46.290475,45.704520,38.477737,38.184759,0
1,43.165380,37.012848,18.750572,12.012085,32.715842,64.162114,76.760155,62.306589,37.208167,19.824824,...,-31.446272,-16.504410,0.781274,16.211432,17.481002,2.929777,-10.937834,-13.574633,-16.211432,0
2,-30.274361,-44.337291,-41.114536,-25.586718,-16.797388,-19.727165,-23.340556,-22.070986,-21.387371,-23.242897,...,-21.973327,-8.008057,-11.719108,-23.145238,-28.125858,-28.516495,-29.590747,-26.270333,-16.504410,0
3,-12.891018,-25.098422,-39.161351,-35.059664,-18.359935,-12.793359,-23.633534,-31.836909,-26.758629,-21.289712,...,-20.117801,-20.020142,-26.367992,-29.883724,-26.563311,-22.363964,-25.098422,-33.301798,-35.450301,0
4,-24.610126,-11.328471,-12.207404,-25.782037,-31.836909,-21.680349,-12.402722,-20.899075,-36.329234,-37.110508,...,-18.555254,0.878933,4.199347,-6.250191,-15.332499,-14.648885,-6.347850,4.297006,9.961241,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
30715,-2.636799,-2.929777,-2.050844,-1.269570,-2.343822,-4.492325,-5.273598,-4.785302,-5.078280,-6.738487,...,-7.519761,-3.613392,1.171911,4.882962,5.371258,1.660207,-4.589984,-9.472945,-11.035493,1
30716,-10.742515,-11.523789,-14.551225,-18.457595,-21.875668,-24.121830,-25.098422,-24.610126,-23.828852,-23.828852,...,-9.668264,-8.203375,-8.105716,-7.617420,-7.715079,-10.156560,-13.574633,-14.844203,-13.379315,1
30717,-11.523789,-11.621448,-13.867611,-16.504410,-17.090365,-15.430158,-13.965270,-15.625477,-18.164617,-16.504410,...,-19.238868,-27.149266,-32.715842,-33.301798,-29.590747,-25.684378,-24.414808,-25.293741,-25.684378,1
30718,-24.512467,-22.754601,-20.606098,-17.676321,-14.160588,-12.012085,-12.305063,-13.672292,-13.769951,-12.891018,...,10.156560,11.328471,11.035493,9.277627,7.519761,7.324442,8.301035,8.594012,7.226783,1
30719,5.468917,4.882962,5.371258,5.566576,4.785302,3.515732,1.464888,-1.074252,-2.832118,-2.148503,...,-1.562548,-1.171911,-0.195318,-0.097659,-1.171911,-1.269570,1.171911,4.589984,6.152532,1

In [5]:
# load features
df_d2 = {}
for i in range(len(pref)):
    fname   = pref[i] + 'features.csv'
    df_d2[i] = pd.read_csv(fname, decimal=',')
#df = pd.read_csv('C4_10_features.csv')
#df_d[4]

In [6]:
df2 = pd.concat(df_d2.values(), ignore_index=True)
#ii = 3
#df = df_d[ii]  
df2

            HDF  Complexity  Mobility  classe
0      1.390931   -1.479577  2.473534       0
1     -0.015578    0.254281 -0.608793       0
2      0.404857   -0.775104  1.209464       0
3      1.767775   -1.228770  2.103808       0
4      0.495654   -0.557916  0.703988       0
...         ...         ...       ...     ...
30715 -1.842650    0.299518 -1.073747       1
30716 -1.193388    0.527062 -0.998790       1
30717 -0.325767    0.794264 -1.089969       1
30718 -2.354177    1.568383 -1.753640       1
30719 -2.018900    1.331529 -1.878392       1

[30720 rows x 4 columns]

In [7]:
df = pd.concat([df1.iloc[:,0:df1.shape[1] -1],df2.iloc[:,0:df2.shape[1] -1], df1.iloc[: , -1:]], ignore_index=True,  axis=1)

In [8]:
# inspect
df

,0,1,2,3,4,5,6,7,8,9,...,94,95,96,97,98,99,100,101,102,103
0,-23.828852,-7.226783,-0.976592,-3.808710,-5.566576,-4.980621,-4.492325,0.683615,11.816767,16.406751,...,36.719871,38.380078,46.290475,45.704520,38.477737,38.184759,1.390931,-1.479577,2.473534,0
1,43.165380,37.012848,18.750572,12.012085,32.715842,64.162114,76.760155,62.306589,37.208167,19.824824,...,16.211432,17.481002,2.929777,-10.937834,-13.574633,-16.211432,-0.015578,0.254281,-0.608793,0
2,-30.274361,-44.337291,-41.114536,-25.586718,-16.797388,-19.727165,-23.340556,-22.070986,-21.387371,-23.242897,...,-23.145238,-28.125858,-28.516495,-29.590747,-26.270333,-16.504410,0.404857,-0.775104,1.209464,0
3,-12.891018,-25.098422,-39.161351,-35.059664,-18.359935,-12.793359,-23.633534,-31.836909,-26.758629,-21.289712,...,-29.883724,-26.563311,-22.363964,-25.098422,-33.301798,-35.450301,1.767775,-1.228770,2.103808,0
4,-24.610126,-11.328471,-12.207404,-25.782037,-31.836909,-21.680349,-12.402722,-20.899075,-36.329234,-37.110508,...,-6.250191,-15.332499,-14.648885,-6.347850,4.297006,9.961241,0.495654,-0.557916,0.703988,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
30715,-2.636799,-2.929777,-2.050844,-1.269570,-2.343822,-4.492325,-5.273598,-4.785302,-5.078280,-6.738487,...,4.882962,5.371258,1.660207,-4.589984,-9.472945,-11.035493,-1.842650,0.299518,-1.073747,1
30716,-10.742515,-11.523789,-14.551225,-18.457595,-21.875668,-24.121830,-25.098422,-24.610126,-23.828852,-23.828852,...,-7.617420,-7.715079,-10.156560,-13.574633,-14.844203,-13.379315,-1.193388,0.527062,-0.998790,1
30717,-11.523789,-11.621448,-13.867611,-16.504410,-17.090365,-15.430158,-13.965270,-15.625477,-18.164617,-16.504410,...,-33.301798,-29.590747,-25.684378,-24.414808,-25.293741,-25.684378,-0.325767,0.794264,-1.089969,1
30718,-24.512467,-22.754601,-20.606098,-17.676321,-14.160588,-12.012085,-12.305063,-13.672292,-13.769951,-12.891018,...,9.277627,7.519761,7.324442,8.301035,8.594012,7.226783,-2.354177,1.568383,-1.753640,1
30719,5.468917,4.882962,5.371258,5.566576,4.785302,3.515732,1.464888,-1.074252,-2.832118,-2.148503,...,-0.097659,-1.171911,-1.269570,1.171911,4.589984,6.152532,-2.018900,1.331529,-1.878392,1

In [9]:
# inspect types 
df.dtypes

0      float64
1      float64
2      float64
3      float64
4      float64
        ...
99     float64
100    float64
101    float64
102    float64
103      int64
Length: 104, dtype: object

In [10]:
df.shape[1]

104

In [11]:
X = df.iloc[:,0:df.shape[1] -1].values
#
#scaler = MinMaxScaler()
#X  = scaler.fit_transform(X.T).T
#
y = df.iloc[: , -1:].values

In [12]:
X

array([[-2.38288522e+01, -7.22678304e+00, -9.76592300e-01, ...,
         1.39093140e+00, -1.47957664e+00,  2.47353401e+00],
       [ 4.31653798e+01,  3.70128483e+01,  1.87505722e+01, ...,
        -1.55777448e-02,  2.54281445e-01, -6.08793221e-01],
       [-3.02743614e+01, -4.43372906e+01, -4.11145360e+01, ...,
         4.04856628e-01, -7.75103955e-01,  1.20946412e+00],
       ...,
       [-1.15237892e+01, -1.16214484e+01, -1.38676107e+01, ...,
        -3.25767015e-01,  7.94264153e-01, -1.08996941e+00],
       [-2.45124668e+01, -2.27546007e+01, -2.06060976e+01, ...,
        -2.35417714e+00,  1.56838296e+00, -1.75364014e+00],
       [ 5.46891690e+00,  4.88296152e+00,  5.37125767e+00, ...,
        -2.01890007e+00,  1.33152936e+00, -1.87839194e+00]])

In [13]:
X_train, X_test, y_train, y_test = train_test_split(X, y,
                                                    train_size=0.8, random_state=18, stratify=y)

In [14]:
# TPOT cfg
tpot = TPOTClassifier(verbosity=2, 
                      scoring="accuracy", 
                      random_state=11,  
                      generations=15, 
                      population_size=15,
                      early_stop=5)

In [15]:
%%time
# fit
tpot.fit(X_train, y_train)

Optimization Progress:   0%|          | 0/240 [00:00<?, ?pipeline/s]

Generation 1 - Current best internal CV score: 0.732218512101991

Generation 2 - Current best internal CV score: 0.732218512101991

Generation 3 - Current best internal CV score: 0.7334393311188496

Generation 4 - Current best internal CV score: 0.7334393311188496

Generation 5 - Current best internal CV score: 0.7334393311188496

Generation 6 - Current best internal CV score: 0.7334393311188496

Generation 7 - Current best internal CV score: 0.7367757491679131

Generation 8 - Current best internal CV score: 0.7367757491679131

Generation 9 - Current best internal CV score: 0.7854818571533813

Generation 10 - Current best internal CV score: 0.7854818571533813

Generation 11 - Current best internal CV score: 0.7854818571533813

Generation 12 - Current best internal CV score: 0.7854818571533813

Generation 13 - Current best internal CV score: 0.7854818571533813

Generation 14 - Current best internal CV score: 0.787679154247099

Generation 15 - Current best internal CV score: 0.7933758764745176

Best pipeline: ExtraTreesClassifier(ExtraTreesClassifier(PCA(input_matrix, iterated_power=10, svd_solver=randomized), bootstrap=True, criterion=gini, max_features=0.8500000000000001, min_samples_leaf=13, min_samples_split=19, n_estimators=100), bootstrap=False, criterion=gini, max_features=0.7000000000000001, min_samples_leaf=6, min_samples_split=2, n_estimators=100)
CPU times: user 8h 58min 9s, sys: 50min 4s, total: 9h 48min 14s
Wall time: 9h 43min 41s

TPOTClassifier(early_stop=5, generations=15, population_size=15,
               random_state=11, scoring='accuracy', verbosity=2)

In [16]:
# TPOT Predict
y_pred = tpot.predict(X_test)

In [17]:
# Results
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.81      0.78      0.79      3072
           1       0.79      0.81      0.80      3072

    accuracy                           0.80      6144
   macro avg       0.80      0.80      0.80      6144
weighted avg       0.80      0.80      0.80      6144

In [18]:
# sanity check (accuracy)
acc = tpot.score(X_test, y_test)
acc

0.7960611979166666

In [19]:
# confusion matrix
cm  = confusion_matrix(y_test, y_pred)
cm

array([[2394,  678],
       [ 575, 2497]])

In [ ]:
if len(pref) == 1:
    pfx = pref[0]
else:
    plx = 'All'
fname = pfx + 'FE_RD_tpot_pipeline_acc_'+ str(round(acc,4))+'.py'
tpot.export('saved_model_TPOT/'+fname)

In [ ]:
fname

In [40]:
#pref[ii]

In [ ]:
df_cm = pd.DataFrame(cm, range(2), range(2))
cmap  = 'jet'#'spring'#'summer'#'winter'#'RdBu'#'PuRd'#'autumn'#'prism'#
pp_matrix(df_cm, cmap=cmap)

In [ ]:
# can we use data from one person to others? vice versa?

In [ ]:
# load val
df_val = pd.read_csv('C4_10_features.csv')  
X_val  = df_val.iloc[:,0:df_val.shape[1] -1].values
y_val  = df_val.iloc[: , -1:].values

In [ ]:
# sanity check (accuracy)
tpot.score(X_val, y_val)

In [ ]:
y_pred_val = tpot.predict(X_val)

In [ ]:
# confusion matrix
cm_val  = confusion_matrix(y_pred_val, y_val)
cm_val

In [ ]:
df.columns = ['X','y']

In [ ]:
#df = df.replace(" ", "," )
#df

In [ ]:
df.iloc[0]['X']

In [ ]:
df.replace("\n", "" )
#df