In [1]:
import tensorflow as tf
#import tensorflow_addons as tfa

tf.get_logger().setLevel("CRITICAL") # "CRITICAL"

# Suppress warnings
import warnings
warnings.filterwarnings('ignore')

2023-05-03 22:09:56.146144: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.10.1

In [2]:
import autokeras as ak
import pandas as pd
import numpy as np
import os
#
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix
#
from sklearn.preprocessing import MinMaxScaler
#
from pretty_confusion_matrix import pp_matrix

In [3]:
#pref = ['C4_1_','C4_5_','C4_6_', 'C4_8_', 'C4_10_']
pref = ['C4_10_']

In [4]:
# load
#pref = ['C4_1_','C4_5_','C4_6_', 'C4_8_', 'C4_10_']
#pref = ['C4_8_']
df_d = {}
for i in range(len(pref)):
    fname   = pref[i] + 'rawdata_open.csv'
    #fname   = pref[i] + 'features.csv'
    df_d[i] = pd.read_csv(fname)
#df = pd.read_csv('C4_10_features.csv')
#df_d[4]

In [5]:
#df = pd.concat(df_d.values(), ignore_index=True)
#ii = 4
#df = df_d[ii] 
df1 = pd.concat(df_d.values(), ignore_index=True)

In [6]:
#pref[ii]
pref

['C4_10_']

In [7]:
# inspect
df1

,x1,x2,x3,x4,x5,x6,x7,x8,x9,x10,...,x92,x93,x94,x95,x96,x97,x98,x99,x100,Class
0,13.574633,0.488296,7.812738,20.996735,18.359935,4.492325,-0.878933,6.152532,12.695700,12.598041,...,-18.750572,3.320414,24.903104,29.004791,21.778008,10.449538,0.195318,2.148503,18.555254,0
1,27.832881,13.769951,-5.957213,-6.933805,1.269570,-6.250191,-23.242897,-23.145238,-5.957213,4.199347,...,-45.899838,-4.297006,58.986175,70.021668,12.109745,-41.895810,-38.184759,-15.723136,-26.172674,0
2,-44.630268,-23.340556,16.406751,21.778008,1.855525,5.078280,25.098422,11.133152,-35.840938,-56.642354,...,25.391400,16.211432,-16.992706,-39.356670,-34.473708,-16.895047,-3.711051,3.027436,6.152532,0
3,4.980621,2.246162,2.148503,1.757866,-2.929777,-6.152532,-3.711051,-7.910398,-27.832881,-42.286447,...,-29.200110,-16.895047,-4.785302,-12.988678,-23.438215,-16.211432,-6.836146,-14.551225,-25.977355,0
4,-21.192053,-10.840175,-12.695700,-16.992706,-8.203375,0.781274,-6.640828,-14.648885,-0.976592,18.359935,...,32.227546,12.012085,-12.500381,-5.664235,23.340556,34.766686,14.160588,-11.035493,-14.258248,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6139,-2.636799,-2.929777,-2.050844,-1.269570,-2.343822,-4.492325,-5.273598,-4.785302,-5.078280,-6.738487,...,-7.519761,-3.613392,1.171911,4.882962,5.371258,1.660207,-4.589984,-9.472945,-11.035493,1
6140,-10.742515,-11.523789,-14.551225,-18.457595,-21.875668,-24.121830,-25.098422,-24.610126,-23.828852,-23.828852,...,-9.668264,-8.203375,-8.105716,-7.617420,-7.715079,-10.156560,-13.574633,-14.844203,-13.379315,1
6141,-11.523789,-11.621448,-13.867611,-16.504410,-17.090365,-15.430158,-13.965270,-15.625477,-18.164617,-16.504410,...,-19.238868,-27.149266,-32.715842,-33.301798,-29.590747,-25.684378,-24.414808,-25.293741,-25.684378,1
6142,-24.512467,-22.754601,-20.606098,-17.676321,-14.160588,-12.012085,-12.305063,-13.672292,-13.769951,-12.891018,...,10.156560,11.328471,11.035493,9.277627,7.519761,7.324442,8.301035,8.594012,7.226783,1
6143,5.468917,4.882962,5.371258,5.566576,4.785302,3.515732,1.464888,-1.074252,-2.832118,-2.148503,...,-1.562548,-1.171911,-0.195318,-0.097659,-1.171911,-1.269570,1.171911,4.589984,6.152532,1

In [8]:
# load features
df_d2 = {}
for i in range(len(pref)):
    fname   = pref[i] + 'features.csv'
    df_d2[i] = pd.read_csv(fname, decimal=',')
#df = pd.read_csv('C4_10_features.csv')
#df_d[4]

In [9]:
df2 = pd.concat(df_d2.values(), ignore_index=True)
#ii = 3
#df = df_d[ii]  
df2

           HDF  Complexity  Mobility  classe
0     1.448775   -1.105723  2.061032       0
1     1.557203   -1.451524  3.303355       0
2     1.453968   -1.492836  3.514876       0
3     1.435601   -1.402319  2.854322       0
4     0.811845    0.205675  0.052083       0
...        ...         ...       ...     ...
6139 -1.842650    0.299518 -1.073747       1
6140 -1.193388    0.527062 -0.998790       1
6141 -0.325767    0.794264 -1.089969       1
6142 -2.354177    1.568383 -1.753640       1
6143 -2.018900    1.331529 -1.878392       1

[6144 rows x 4 columns]

In [10]:
df = pd.concat([df1.iloc[:,0:df1.shape[1] -1],df2.iloc[:,0:df2.shape[1] -1], df1.iloc[: , -1:]], ignore_index=True,  axis=1)

In [11]:
df

,0,1,2,3,4,5,6,7,8,9,...,94,95,96,97,98,99,100,101,102,103
0,13.574633,0.488296,7.812738,20.996735,18.359935,4.492325,-0.878933,6.152532,12.695700,12.598041,...,29.004791,21.778008,10.449538,0.195318,2.148503,18.555254,1.448775,-1.105723,2.061032,0
1,27.832881,13.769951,-5.957213,-6.933805,1.269570,-6.250191,-23.242897,-23.145238,-5.957213,4.199347,...,70.021668,12.109745,-41.895810,-38.184759,-15.723136,-26.172674,1.557203,-1.451524,3.303355,0
2,-44.630268,-23.340556,16.406751,21.778008,1.855525,5.078280,25.098422,11.133152,-35.840938,-56.642354,...,-39.356670,-34.473708,-16.895047,-3.711051,3.027436,6.152532,1.453968,-1.492836,3.514876,0
3,4.980621,2.246162,2.148503,1.757866,-2.929777,-6.152532,-3.711051,-7.910398,-27.832881,-42.286447,...,-12.988678,-23.438215,-16.211432,-6.836146,-14.551225,-25.977355,1.435601,-1.402319,2.854322,0
4,-21.192053,-10.840175,-12.695700,-16.992706,-8.203375,0.781274,-6.640828,-14.648885,-0.976592,18.359935,...,-5.664235,23.340556,34.766686,14.160588,-11.035493,-14.258248,0.811845,0.205675,0.052083,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6139,-2.636799,-2.929777,-2.050844,-1.269570,-2.343822,-4.492325,-5.273598,-4.785302,-5.078280,-6.738487,...,4.882962,5.371258,1.660207,-4.589984,-9.472945,-11.035493,-1.842650,0.299518,-1.073747,1
6140,-10.742515,-11.523789,-14.551225,-18.457595,-21.875668,-24.121830,-25.098422,-24.610126,-23.828852,-23.828852,...,-7.617420,-7.715079,-10.156560,-13.574633,-14.844203,-13.379315,-1.193388,0.527062,-0.998790,1
6141,-11.523789,-11.621448,-13.867611,-16.504410,-17.090365,-15.430158,-13.965270,-15.625477,-18.164617,-16.504410,...,-33.301798,-29.590747,-25.684378,-24.414808,-25.293741,-25.684378,-0.325767,0.794264,-1.089969,1
6142,-24.512467,-22.754601,-20.606098,-17.676321,-14.160588,-12.012085,-12.305063,-13.672292,-13.769951,-12.891018,...,9.277627,7.519761,7.324442,8.301035,8.594012,7.226783,-2.354177,1.568383,-1.753640,1
6143,5.468917,4.882962,5.371258,5.566576,4.785302,3.515732,1.464888,-1.074252,-2.832118,-2.148503,...,-0.097659,-1.171911,-1.269570,1.171911,4.589984,6.152532,-2.018900,1.331529,-1.878392,1

In [12]:
# inspect types 
df.dtypes

0      float64
1      float64
2      float64
3      float64
4      float64
        ...
99     float64
100    float64
101    float64
102    float64
103      int64
Length: 104, dtype: object

In [13]:
df.shape[1]

104

In [14]:
X = df.iloc[:,0:df.shape[1] -1].values
#
#scaler = MinMaxScaler()
#X  = scaler.fit_transform(X.T).T
#
y = df.iloc[: , -1:].values

In [15]:
X

array([[ 13.57463301,   0.48829615,   7.81273843, ...,   1.4487754 ,
         -1.1057231 ,   2.06103199],
       [ 27.83288064,  13.76995148,  -5.95721305, ...,   1.55720313,
         -1.45152361,   3.30335511],
       [-44.63026826, -23.34055605,  16.40675069, ...,   1.45396755,
         -1.49283585,   3.51487574],
       ...,
       [-11.52378918, -11.62144841, -13.86761071, ...,  -0.32576701,
          0.79426415,  -1.08996941],
       [-24.51246681, -22.75460067, -20.6060976 , ...,  -2.35417714,
          1.56838296,  -1.75364014],
       [  5.4689169 ,   4.88296152,   5.37125767, ...,  -2.01890007,
          1.33152936,  -1.87839194]])

In [16]:
y

array([[0],
       [0],
       [0],
       ...,
       [1],
       [1],
       [1]])

In [20]:
#
path     = os.getcwd()
folder   = 'saved_model_AK'
#
if not os.path.exists(path+'/'+folder):
    os.mkdir(path+'/'+folder)

#
l_SEEDS  = list(range(1,10000))#[658,847,688,84,535,396]
n_seeds  = 5
#SEED     = 98741
n_trials = 50
l_TUNER  = ["hyperband",'random','greedy','bayesian']#['random','greedy','bayesian']#['hyperband']#

ERROR! Session/line number was not unique in database. History logging moved to new session 5126

In [21]:
if len(pref) == 1:
    pfx = pref[0]
else:
    pfx = 'All_'
#
if X.shape[1] == 103:
    inp = 'mix_FE_RD_'
elif X.shape[1] == 100: 
    inp = 'RD_only_'
elif X.shape[1] == 3:
    inp = 'FE_only_'

In [22]:
pfx,inp

('C4_10_', 'mix_FE_RD_')

In [ ]:
%%time
#for i in range(n_seeds):
while True:
    
    # some hyper parameters
    TUNER = np.random.choice(l_TUNER)
    SEED  = int(np.random.choice(l_SEEDS))
    RS1   = 15#int(np.random.choice(list(range(1,10000))))
    #RS2  = int(np.random.choice(l_SEEDS))

    # train test split
    X_train, X_test, y_train, y_test = train_test_split(X, y,
                                                        train_size=0.8, random_state=RS1, stratify=y)
    
    # regressor
    clf = ak.StructuredDataClassifier(num_classes = 2,overwrite=True, 
                                  max_trials=n_trials, 
                                  objective='val_accuracy', 
                                  seed = SEED, tuner = TUNER,
                                  max_model_size=None)
    
    # fit
    clf.fit(x=X_train, y=y_train, validation_data =(X_test, y_test))
    
    # ak Predict
    y_pred = clf.predict(X_test)
    
    # Results
    # confusion matrix
    cm   = confusion_matrix(y_test, y_pred)
    print(cm)
    #
    print(classification_report(y_test, y_pred))
    cr_d = classification_report(y_test, y_pred, output_dict=True)
    acc  = cr_d['accuracy']
    rc1  = cr_d['1']['recall']
    #
    if cr_d['accuracy'] > 0.98:
        print('Saving model...')
        model = clf.export_model()
        model.summary()
        #mname = "model"+'_r2_'+str(round(reg_results(y_test,y_pred)[0],4))+'_'+TUNER#'.h5'
        mname = pfx+inp+'acc_'+str(round(acc,4))+'_rc1_'+str(round(rc1,4))+'_'+TUNER+'_rs_'+str(RS1)
        try:
            model.save(folder+'/'+mname)#, save_format="tf")
        except Exception:
            model.save(folder+'/'+mname+".h5")
        #model.save(folder+'/'+mname+'.tf') # try .h5 too
        # model
        tf.keras.utils.plot_model(model, to_file=folder+'/'+mname+'/model.png', 
                                  rankdir='TB', 
                                  show_shapes=True, show_layer_names=True, expand_nested=False, dpi=96)

Trial 23 Complete [00h 02m 01s]
val_accuracy: 0.9764035940170288

Best val_accuracy So Far: 0.9837266206741333
Total elapsed time: 01h 05m 18s

Search: Running Trial #24

Hyperparameter    |Value             |Best Value So Far
structured_data...|False             |False
structured_data...|True              |True
structured_data...|3                 |1
structured_data...|1024              |1024
structured_data...|0                 |0
structured_data...|16                |1024
classification_...|0.5               |0
optimizer         |adam              |adam
learning_rate     |1e-05             |1e-05
structured_data...|1024              |16

Epoch 1/1000
154/154 [==============================] - 1s 9ms/step - loss: 0.7177 - accuracy: 0.6085 - val_loss: 0.6156 - val_accuracy: 0.7144
Epoch 2/1000
154/154 [==============================] - 1s 5ms/step - loss: 0.6529 - accuracy: 0.6604 - val_loss: 0.5666 - val_accuracy: 0.7217
Epoch 3/1000
154/154 [==============================] - 1s 5ms/step - loss: 0.6334 - accuracy: 0.6743 - val_loss: 0.5364 - val_accuracy: 0.7331
Epoch 4/1000
154/154 [==============================] - 1s 6ms/step - loss: 0.6111 - accuracy: 0.6930 - val_loss: 0.5207 - val_accuracy: 0.7461
Epoch 5/1000
154/154 [==============================] - 1s 5ms/step - loss: 0.5950 - accuracy: 0.6968 - val_loss: 0.5127 - val_accuracy: 0.7526
Epoch 6/1000
154/154 [==============================] - 1s 5ms/step - loss: 0.5948 - accuracy: 0.7007 - val_loss: 0.5005 - val_accuracy: 0.7600
Epoch 7/1000
154/154 [==============================] - 1s 5ms/step - loss: 0.5744 - accuracy: 0.7202 - val_loss: 0.4882 - val_accuracy: 0.7657
Epoch 8/1000
154/154 [==============================] - 1s 6ms/step - loss: 0.5553 - accuracy: 0.7241 - val_loss: 0.4693 - val_accuracy: 0.7746
Epoch 9/1000
154/154 [==============================] - 1s 5ms/step - loss: 0.5310 - accuracy: 0.7377 - val_loss: 0.4507 - val_accuracy: 0.7852
Epoch 10/1000
154/154 [==============================] - 1s 5ms/step - loss: 0.4993 - accuracy: 0.7632 - val_loss: 0.4291 - val_accuracy: 0.7966
Epoch 11/1000
154/154 [==============================] - 1s 5ms/step - loss: 0.4792 - accuracy: 0.7707 - val_loss: 0.4061 - val_accuracy: 0.8153
Epoch 12/1000
154/154 [==============================] - 1s 5ms/step - loss: 0.4503 - accuracy: 0.7994 - val_loss: 0.3873 - val_accuracy: 0.8259
Epoch 13/1000
154/154 [==============================] - 1s 5ms/step - loss: 0.4176 - accuracy: 0.8181 - val_loss: 0.3622 - val_accuracy: 0.8356
Epoch 14/1000
154/154 [==============================] - 1s 5ms/step - loss: 0.3967 - accuracy: 0.8234 - val_loss: 0.3424 - val_accuracy: 0.8511
Epoch 15/1000
154/154 [==============================] - 1s 5ms/step - loss: 0.3659 - accuracy: 0.8431 - val_loss: 0.3203 - val_accuracy: 0.8641
Epoch 16/1000
154/154 [==============================] - 1s 5ms/step - loss: 0.3476 - accuracy: 0.8498 - val_loss: 0.3039 - val_accuracy: 0.8755
Epoch 17/1000
154/154 [==============================] - 1s 5ms/step - loss: 0.3202 - accuracy: 0.8612 - val_loss: 0.2898 - val_accuracy: 0.8926
Epoch 18/1000
154/154 [==============================] - 1s 5ms/step - loss: 0.3032 - accuracy: 0.8698 - val_loss: 0.2733 - val_accuracy: 0.8967
Epoch 19/1000
154/154 [==============================] - 1s 5ms/step - loss: 0.2852 - accuracy: 0.8867 - val_loss: 0.2610 - val_accuracy: 0.9032
Epoch 20/1000
154/154 [==============================] - 1s 6ms/step - loss: 0.2637 - accuracy: 0.8966 - val_loss: 0.2468 - val_accuracy: 0.9081
Epoch 21/1000
154/154 [==============================] - 1s 6ms/step - loss: 0.2537 - accuracy: 0.9030 - val_loss: 0.2366 - val_accuracy: 0.9048
Epoch 22/1000
154/154 [==============================] - 1s 5ms/step - loss: 0.2317 - accuracy: 0.9091 - val_loss: 0.2284 - val_accuracy: 0.9178
Epoch 23/1000
154/154 [==============================] - 1s 5ms/step - loss: 0.2177 - accuracy: 0.9162 - val_loss: 0.2227 - val_accuracy: 0.9219
Epoch 24/1000
154/154 [==============================] - 1s 6ms/step - loss: 0.2119 - accuracy: 0.9200 - val_loss: 0.2165 - val_accuracy: 0.9219
Epoch 25/1000
117/154 [=====================>........] - ETA: 0s - loss: 0.1962 - accuracy: 0.9290

In [ ]:
cr_d = classification_report(y_test, y_pred, output_dict=True)
acc  = cr_d['accuracy']
rc1  = cr_d['1']['recall']
#
if cr_d['accuracy'] > 0.9:
    print('Saving model...')
    model = clf.export_model()
    model.summary()
    #mname = "model"+'_r2_'+str(round(reg_results(y_test,y_pred)[0],4))+'_'+TUNER#'.h5'
    mname = 'acc_'+str(round(acc,4))+'_rc1_'+str(round(rc1,4))+'_'+TUNER+'_rs_'+str(RS1)
    try:
        model.save(folder+'/'+mname)#, save_format="tf")
    except Exception:
        model.save(folder+'/'+mname+".h5")
    #model.save(folder+'/'+mname+'.tf') # try .h5 too
    # model
    tf.keras.utils.plot_model(model, to_file=folder+'/'+mname+'/model.png', 
                              rankdir='TB', 
                              show_shapes=True, show_layer_names=True, expand_nested=False, dpi=96)

In [ ]:
# autoKeras cfg
#l_SEED   = [658,847,688,84,535,396]
#n_seeds  = 1
SEED     = 19
n_trials = 100
TUNER    = "hyperband"#'random'#'greedy'#"'bayesian'#
#
clf = ak.StructuredDataClassifier(num_classes = 2,overwrite=True, 
                                  max_trials=n_trials, 
                                  objective='val_accuracy', 
                                  seed = SEED, tuner = TUNER)


#
l_SEEDS  = list(range(1,100))#[658,847,688,84,535,396]
n_seeds  = 3
#SEED     = 98741
n_trials = 100
l_TUNER    = ["hyperband",'random','greedy','bayesian']#['random','greedy','bayesian']#['random']#

In [ ]:
%%time
# fit

#
clf.fit(x=X_train, y=y_train, validation_data =(X_test, y_test))

In [ ]:
# ak Predict
#
y_pred = clf.predict(X_test)

In [ ]:
# Results
print(classification_report(y_test, y_pred))

In [ ]:
# sanity check (accuracy)
print(clf.evaluate(X_test, y_test))
#tpot.score(X_test, y_test)

In [ ]:
# confusion matrix
cm  = confusion_matrix(y_test, y_pred)
cm

In [ ]:
from pretty_confusion_matrix import pp_matrix

In [ ]:
#pref[ii]

In [ ]:
df_cm = pd.DataFrame(cm, range(2), range(2))
cmap  = 'jet'#'spring'#'summer'#'winter'#'RdBu'#'PuRd'#'autumn'#'prism'#
pp_matrix(df_cm, cmap=cmap)

In [ ]:
# can we use data from one person to others? vice versa?

In [ ]:
# load val
df_val = pd.read_csv('C4_10_features.csv')  
X_val  = df_val.iloc[:,0:df_val.shape[1] -1].values
y_val  = df_val.iloc[: , -1:].values

In [ ]:
# sanity check (accuracy)
tpot.score(X_val, y_val)

In [ ]:
y_pred_val = tpot.predict(X_val)

In [ ]:
# confusion matrix
cm_val  = confusion_matrix(y_pred_val, y_val)
cm_val

In [ ]:
df.columns = ['X','y']

In [ ]:
#df = df.replace(" ", "," )
#df

In [ ]:
df.iloc[0]['X']

In [ ]:
df.replace("\n", "" )
#df